name: Hugo build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'

    - name: Build
      run: hugo --baseURL="https://www.ifge.at"
      env:
        TZ: Europe/Vienna 

    - name: Deploy to FTP 
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp://host38.ssl-net.net
        user: fcbp_at_ifge_leichtware
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "public"
        remoteDir: "/ifge.at"
